[package]
name = "ebpf-monitor-user"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { git = "https://github.com/aya-rs/aya" }
aya-log = { git = "https://github.com/aya-rs/aya" }
anyhow = "1"
env_logger = "0.10"
log = "0.4"
tokio = { version = ">=1.38.0, <2.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "time"] }
ebpf-monitor-common = { path = "../common", features = ["user"] }
rlimit = "0.10"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
anyhow = "1"
